"""Monitoring package."""

from .metrics import (
    ACTIVE_WORKERS,
    QUEUE_DEPTH,
    TASKS_COMPLETED,
    TASKS_FAILED,
    TASKS_SUBMITTED,
    WORKER_CAPACITY_UTILIZATION,
    observe_http_request,
    observe_task_duration,
    observe_task_wait,
    prometheus_response,
    record_task_completed,
    record_task_failed,
    record_task_submitted,
    set_active_workers,
    set_queue_depth,
    set_worker_capacity_utilization,
)
from .worker_metrics import (
    WORKER_AVG_DURATION,
    WORKER_ERROR_RATE,
    WORKER_RESTART_COUNT,
    WORKER_TASK_DURATION_HISTOGRAM,
    WORKER_TASK_RATE,
    WORKER_UPTIME,
    WorkerMetricsTracker,
    get_worker_metrics_tracker,
)

__all__ = [
    "ACTIVE_WORKERS",
    "QUEUE_DEPTH",
    "TASKS_COMPLETED",
    "TASKS_FAILED",
    "TASKS_SUBMITTED",
    "WORKER_CAPACITY_UTILIZATION",
    "WORKER_AVG_DURATION",
    "WORKER_ERROR_RATE",
    "WORKER_RESTART_COUNT",
    "WORKER_TASK_DURATION_HISTOGRAM",
    "WORKER_TASK_RATE",
    "WORKER_UPTIME",
    "WorkerMetricsTracker",
    "get_worker_metrics_tracker",
    "observe_http_request",
    "observe_task_duration",
    "observe_task_wait",
    "prometheus_response",
    "record_task_completed",
    "record_task_failed",
    "record_task_submitted",
    "set_active_workers",
    "set_queue_depth",
    "set_worker_capacity_utilization",
]
