"""Application constants"""

# Task Priority Levels
TASK_PRIORITY_CRITICAL = 1
TASK_PRIORITY_HIGH = 2
TASK_PRIORITY_MEDIUM = 5
TASK_PRIORITY_LOW = 10

TASK_PRIORITIES = {
    "CRITICAL": TASK_PRIORITY_CRITICAL,
    "HIGH": TASK_PRIORITY_HIGH,
    "MEDIUM": TASK_PRIORITY_MEDIUM,
    "LOW": TASK_PRIORITY_LOW,
}

# Task Statuses
TASK_STATUS_PENDING = "PENDING"
TASK_STATUS_SCHEDULED = "SCHEDULED"
TASK_STATUS_RUNNING = "RUNNING"
TASK_STATUS_COMPLETED = "COMPLETED"
TASK_STATUS_FAILED = "FAILED"
TASK_STATUS_CANCELLED = "CANCELLED"
TASK_STATUS_TIMEOUT = "TIMEOUT"

TASK_STATUSES = [
    TASK_STATUS_PENDING,
    TASK_STATUS_SCHEDULED,
    TASK_STATUS_RUNNING,
    TASK_STATUS_COMPLETED,
    TASK_STATUS_FAILED,
    TASK_STATUS_CANCELLED,
    TASK_STATUS_TIMEOUT,
]

# Worker Statuses
WORKER_STATUS_ACTIVE = "ACTIVE"
WORKER_STATUS_IDLE = "IDLE"
WORKER_STATUS_BUSY = "BUSY"
WORKER_STATUS_DEAD = "DEAD"
WORKER_STATUS_PAUSED = "PAUSED"

WORKER_STATUSES = [
    WORKER_STATUS_ACTIVE,
    WORKER_STATUS_IDLE,
    WORKER_STATUS_BUSY,
    WORKER_STATUS_DEAD,
    WORKER_STATUS_PAUSED,
]

# Campaign Statuses
CAMPAIGN_STATUS_DRAFT = "DRAFT"
CAMPAIGN_STATUS_SCHEDULED = "SCHEDULED"
CAMPAIGN_STATUS_RUNNING = "RUNNING"
CAMPAIGN_STATUS_PAUSED = "PAUSED"
CAMPAIGN_STATUS_COMPLETED = "COMPLETED"
CAMPAIGN_STATUS_FAILED = "FAILED"

CAMPAIGN_STATUSES = [
    CAMPAIGN_STATUS_DRAFT,
    CAMPAIGN_STATUS_SCHEDULED,
    CAMPAIGN_STATUS_RUNNING,
    CAMPAIGN_STATUS_PAUSED,
    CAMPAIGN_STATUS_COMPLETED,
    CAMPAIGN_STATUS_FAILED,
]

# Email Statuses
EMAIL_STATUS_PENDING = "PENDING"
EMAIL_STATUS_SENT = "SENT"
EMAIL_STATUS_FAILED = "FAILED"
EMAIL_STATUS_BOUNCED = "BOUNCED"
EMAIL_STATUS_UNSUBSCRIBED = "UNSUBSCRIBED"

EMAIL_STATUSES = [
    EMAIL_STATUS_PENDING,
    EMAIL_STATUS_SENT,
    EMAIL_STATUS_FAILED,
    EMAIL_STATUS_BOUNCED,
    EMAIL_STATUS_UNSUBSCRIBED,
]

# Retry Configuration
DEFAULT_MAX_RETRIES = 5
DEFAULT_RETRY_BACKOFF_SECONDS = 2
RETRY_BACKOFF_MULTIPLIER = 2

# Timeouts (in seconds)
DEFAULT_TASK_TIMEOUT = 300
WORKER_HEARTBEAT_INTERVAL = 10
WORKER_DEAD_TIMEOUT = 30
SCHEDULER_CHECK_INTERVAL = 5

# Queue Names
QUEUE_PREFIX = "task:queue"
TASK_META_PREFIX = "task:meta"
WORKER_PREFIX = "worker"
WORKER_REGISTRY_KEY = "worker:registry"
SCHEDULED_TASKS_KEY = "task:scheduled"
CAMPAIGN_PROGRESS_PREFIX = "campaign"
TASK_DEPENDENCIES_PREFIX = "task:dependencies"
TASK_COMPLETED_STREAM = "task:completed"
RATE_LIMIT_PREFIX = "rate_limit"

# Limits
RATE_LIMIT_PER_MINUTE = 100
RATE_LIMIT_PER_HOUR = 1000
DEFAULT_CAMPAIGN_RATE_LIMIT = 100
MAX_CAMPAIGN_RATE_LIMIT = 1000

# DLQ Configuration
DLQ_RETENTION_DAYS = 30

# Log Levels
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"

# JWT
JWT_ALGORITHM = "HS256"
JWT_TOKEN_TYPE = "bearer"

# API Versions
API_VERSION = "v1"
API_BASE_PATH = f"/api/{API_VERSION}"

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Response Messages
MSG_TASK_CREATED = "Task created successfully"
MSG_TASK_CANCELLED = "Task cancelled successfully"
MSG_TASK_RETRIED = "Task retry queued successfully"
MSG_CAMPAIGN_STARTED = "Campaign started successfully"
MSG_CAMPAIGN_PAUSED = "Campaign paused successfully"
MSG_WORKER_PAUSED = "Worker paused successfully"

# Error Messages
ERR_TASK_NOT_FOUND = "Task not found"
ERR_WORKER_NOT_FOUND = "Worker not found"
ERR_CAMPAIGN_NOT_FOUND = "Campaign not found"
ERR_INVALID_PRIORITY = "Invalid task priority"
ERR_INVALID_STATUS = "Invalid status"
ERR_RATE_LIMITED = "Rate limit exceeded"
ERR_UNAUTHORIZED = "Unauthorized"
ERR_FORBIDDEN = "Forbidden"
